language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn test
  - yarn check-coverage
  - yarn build
after_success:
  - yarn semantic-release
  - yarn coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
